### ISSUE TITLE
Lectura 5

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/Kotlin_Readings#1]
# Requierements

## Task
Androd development patters (Phil Dutson 2016)
- [ ] Capitulo 3
- [ ] Capitulo 4
- [ ] Introducción a los activitys
       🔗 [Link](https://developer.android.com/guide/components/activities/intro-activities?hl=es-419)
- [ ] Ciclo de vida de los activitys
       🔗 [Link](https://developer.android.com/guide/components/activities/activity-lifecycle?hl=es-419)
- [ ] Cambios de estado en los activitys
       🔗 [Link](https://developer.android.com/guide/components/activities/state-changes?hl=es-419)
